version: '3.7'

services:
  app:
    image: 'benbergstein/bread:latest'
    command: ["serve"]
    networks:
       - haproxy-controller_haproxy-controller

networks:
   haproxy-controller_haproxy-controller:
      external: true
